### ISSUE TITLE
bash template for PlexRequests update is off and needs to be updated.

### ISSUE THREAD

**Issue by RXWatcher1** [QuickBox/quickbox_setup#1]
It's not correct and needs to be updated.

1. PlexRequests.sqlite need to be renamed to Ombi.sqlite
2.  "Stopping PlexRequsts Service" has a typo in it
3. needs to account for the fact that we're moving from PlexRequests to Ombi but also Ombi to Ombi so some type of if/else statement to account for that.

**Comment by JMSDOnline** [comment]
Since you know the new Ombi, could you possibly submit a pull for this @RXWatcher1

**Comment by RXWatcher1** [comment]
Agreed..need time. I dont have things pointing here yet.

**Comment by JMSDOnline** [comment]
Updated here:
https://github.com/QuickBox/quickbox_setup/commit/0526437fef6e1f81558fc6c2fdc8641d08862ffe
