### ISSUE TITLE
autodl-trackers not updating properly

### ISSUE THREAD

**Issue by gnadlr** [QuickBox/quickbox_setup#2]
After installed, I noticed trackers list in rutorrent is not up-to-date. I tried updating through the autodl-irssi/update tab in rutorrent. It reports succesful update with latest versions:

```
you are using the latest autodl-trackers v260
you are using the latest autodl-irssi v1.62
```

However, after "Reload Trackers", as well as reload autodl-irssi and rtorrent in dashboard, the trackers list is still the same (v254). A further look into ~/.irssi/scripts/AutodlIrssi/trackers/ shows that update was not made.

I think this might be an issue from autodl-irssi side, since they don't update the link to the latest version of autodl-trackers: https://github.com/autodl-community/autodl-irssi/tree/master/AutodlIrssi  

Can Quickbox fix to pull the latest trackers files directly from https://github.com/autodl-community/autodl-trackers?

For now the workaround is to manually download the autodl-trackers repo.

**Comment by JMSDOnline** [comment]
As per the install of AutoDL we have the following function performed on install:

```
# function autodl to install autodl irssi scripts (27)
function _autodl() {
  mkdir -p "/home/${username}/.irssi/scripts/autorun/" >>"${OUTTO}" 2>&1
  cd "/home/${username}/.irssi/scripts/"
  wget -qO autodl-irssi.zip https://github.com/autodl-community/autodl-irssi/releases/download/community-v1.62/autodl-irssi-community-v1.62.zip
  unzip -o autodl-irssi.zip >>"${OUTTO}" 2>&1
  rm autodl-irssi.zip
  cp autodl-irssi.pl autorun/
  mkdir -p "/home/${username}/.autodl" >>"${OUTTO}" 2>&1
  touch "/home/${username}/.autodl/autodl.cfg"
  chown ${username}: /home/${username}/.autodl/autodl.cfg
  touch /install/.autodlirssi.lock

cat >"/home/${username}/.autodl/autodl2.cfg"<<ADC
[options]
gui-server-port = ${AUTODLPORT}
gui-server-password = ${AUTODLPASSWORD}
ADC

  chown -R "${username}.${username}" "/home/${username}/.irssi/"
  chown -R "${username}.${username}" "/home/${username}"
}
```

This is pulling the latest v1.62 release. 

>However, after "Reload Trackers", as well as reload autodl-irssi and rtorrent in dashboard, the trackers list is still the same (v254). A further look into ~/.irssi/scripts/AutodlIrssi/trackers/ shows that update was not made.

I wonder if this is happening due to how the trackers repo is stored as a submodule within the autodl-community repo. Perhaps if we initiated a recursive git clone on the install, rather than grabbing version releases, we'd have been luck at this. Although, it should be able to pull the tracker updates without issue. I will look into this shortly.

**Comment by gnadlr** [comment]
Yeah. Instead of grabbing the zip (with bundle irssi v1.62 and trackers v254), we should clone the autodl-irssi repo but ignore the trackers submodule, then add the submodule from autodl-trackers

**Comment by JMSDOnline** [comment]
I'll test this as a recursive and see if it results in better success... then we'll easily be on the master without the need for grabbing archives (I prefer it that way anyhow).

**Comment by gnadlr** [comment]
If you don't like git clone, how about adding a script to grab the archives at https://github.com/autodl-community/autodl-trackers/releases and extract on top of ~/.irssi/scripts/AutodlIrssi/trackers/ ?

**Comment by JMSDOnline** [comment]
I am speaking of using git clone... however to grab submodules properly a --recursive flag must be added. No worries, it will be addressed ;)

**Comment by gnadlr** [comment]
I'm sure you know better than me, but what I wanted to say is: the trackers submodule in the autodl-community/autodl-irssi repo is not up to date, it points to v254, latest is v260. So a git clone probably won't be any difference. The latest version v260 is at the autodl-community/autodl-trackers repo.

**Comment by JMSDOnline** [comment]
I will work on adding a possible update command as well as adjusting how the initial installer handles the inclusion of AutoDL.

Something along the lines of..
```
cd /home/$USER/.irssi/scripts/AutodlIrssi
rm -rf trackers
git clone https://github.com/autodl-community/autodl-trackers.git trackers
chown -R $USER:$USER trackers
```

**Comment by gnadlr** [comment]
Yeah, I think that's one way do it.  

However, is there any particular reason to `curl` autodl-irssi but `git clone` autodl-trackers? I see you've updated the `curl `command for autodl-irssi, then shouldn't we also `curl` autodl-trackers?  

Otherwise, using `git clone` for both definitely help staying on the master.

**Comment by JMSDOnline** [comment]
> However, is there any particular reason to curl autodl-irssi but git clone autodl-trackers? I see you've updated the curlcommand for autodl-irssi, then shouldn't we also curl autodl-trackers?

The reasoning behind the `curl` is to grab the latest version from the browser within the releases. This is just a temporary resolution however as I will be updating it soon with a better `git clone/pull` install/update function.

The `git clone` for the trackers is a temporary solution to update them now until I push a more elegant solution that doesn't potentially bork someones install of autdl.

**Comment by gnadlr** [comment]
I ran a quick test of the new commits (fresh installation on Debian 8.7). The new .tracker files (UHDBits, PassTheHeadphones) were there, so the curl and unzip functions worked.

However, the extracted .tracker files v260 were somehow overwritten with the old version v254. You can check this by comparing .tracker files that were changed in version later than v254 (for example What.CD should be removed in v260 but is there, Bit-HDTV was changed but the .tracker file is an old version.)  

Are you accidentally overwritting the /trackers folder somehow?

**Comment by JMSDOnline** [comment]
I really don't think this is an issue on the part of QuickBox. I will continue to look into this, however, this should probably be asked of [thebigmunch](https://github.com/thebigmunch) if this is a known issue.

**Comment by gnadlr** [comment]
Here's the step I took (tried twice):  

1/ Fresh installation of Debian 8.7. Ran Quickbox installation script. Reboot
2/ Checked /trackers folder and found what I described above (v254 overwriting v260).
3/ Open rutorrent, autodl-irssi tab and clicked update. Update reports success.
4/ Checked back in /trackers folder, found v254 (v260 files gone).

For comparison, I run another seedbox installation script (https://github.com/arakasi72/rtinst), and verified that the inner update function of autodl worked normally. So not an issue on [thebigmunch](https://github.com/thebigmunch) side.

In fact, the original issue is that the inner update function of autodl-irssi on Quickbox does not work for me.  A quick search on the forum shows users with the same issue https://plaza.quickbox.io/t/autodl-irssi-tracker-list-problem/1784

Though the inner update function of autodl-irssi seems to be okay on your part (we don't really need the "fix" to curl autodl-trackers if it works).

**Comment by JMSDOnline** [comment]
Running through very old threads in the Plaza reveal that this issue is for some reason more linked to Debian than Ubuntu... now to figure out why that is. Specifically, there is no step different to what is recommended by thebigmunch. I am not hitting this issue personally and tried on another Ubuntu install (same results, all updated without issue and changes match). 

What's additionally puzzling is you say that arakasi script works fine... he literally has the very same install method. I'll definitely need a weekend to dig into this.

With that said, I will fire up a Debian install at first chance to test a few "theories". However, this is a very loose speculation on my end, as there is no reason a simple pull would be any different from one OS to the next.

**Comment by manwithnoname** [comment]
Not much to add but just to report that this has happened to me on 2 different servers / Ubuntu Server 16.04 Quickbox installations.

Never had a problem with autodl-irssi using either Arakari72 script or this one -> [https://jes.sc/kb/rTorrent+ruTorrent-Seedbox-Guide.php](url)

**Comment by gnadlr** [comment]
I'm able to reproduce the issue on both Debian 8.7 and Ubuntu 16.04.1 (Digital Ocean).

Here's what I've found:

At first launch of rutorrent, I check version of autodl-irssi. It turns out the installed version of autodl-irssi is v1.60, which is strange since we already unzip v1.62.

I look a bit into the code, and since the version of autodl-irssi stored inside /skel is 1.60, I think this might have something to do with the _makedir function,

**Comment by JMSDOnline** [comment]
> I look a bit into the code, and since the version of autodl-irssi stored inside /skel is 1.60, I think this might have something to do with the _makedir function.

**Noted** You're absolutely right. I spaced that we still have that lingering in the master skel. I'll push an update to that promptly. Well spotted!

**Comment by gnadlr** [comment]
Thanks. Glad it helps!

Is it because /skel overwriting the extracted zips, or because the zips are extracted on top of /skel but cannot overwrite?  

Either way, why do we include /AutodlIrssi inside /skel, since we already have scripts to grab the latest zips?

**Comment by JMSDOnline** [comment]
Well, there is no reason and this is an incredible oversight on my part as that /skel (that entire function) hasn't been visited in a long time. I will more than likely just include the port arrangements directly inside the _autodl function... seeing as how the /skel should really be just that.

Sometimes my brain is backwards.

**Comment by gnadlr** [comment]
Well, we've all been there :)
