### ISSUE TITLE
Leftover files from deleteSeedboxUser

### ISSUE THREAD

**Issue by d2dyno** [QuickBox/quickbox_setup#3]
When I create a user from root with "createSeedboxUser", then remove the user with "deleteSeedboxUser", there is many files leftover. Specifically "$user.info.db" and "$user.info". Is this intentional? Or can I modify the delete command code to remove these traces? For my organisational taste, it's bothersome to see these leftovers.

Relevant line of code: https://github.com/QuickBox/quickbox_setup/blob/master/templates/bashrc.template#L1156

I'm more than happy to work on this, just need to know if it was designed that way or not.

**Comment by JMSDOnline** [comment]
These files can safely be removed. The issue arises from this being a byproduct of how our initial installer worked. We didn't create user dump files. Then I included it and never wrote the removal for those little extra files as I focused on the removal of key files wherein the users data should not remain... (ie; htpasswd... etc) 

You may even find some leftover user..conf files in apache `sites-enabled` as well. These can additionally be removed. I do plan on having them removed... however, the focus at the moment is working on Dockerizing QuickBox and it's subsequent Eco-System. This includes placing on Nginx also. Therefore, you may find a few hidden gems that drive your OCD crazy... this intended to be cleaned and made much lighter.

Thanks for pointing it out and reminding me. 😄

**Comment by d2dyno** [comment]
Ah ok, sweet. I'll put the relevant lines in then and start a PR.
